# Lab | Data Structuring and Combining Data

## Challenge 1: Combining & Cleaning Data

In this challenge, we will be working with the customer data from an insurance company, as we did in the two previous labs. The data can be found here:
- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv

But this time, we got new data, which can be found in the following 2 CSV files located at the links below.

- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file2.csv
- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file3.csv

Note that you'll need to clean and format the new data.

Observation:
- One option is to first combine the three datasets and then apply the cleaning function to the new combined dataset
- Another option would be to read the clean file you saved in the previous lab, and just clean the two new files and concatenate the three clean datasets

In [1]:
import pandas as pd

In [2]:
url1="https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv"
url2="https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file2.csv"
url3="https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file3.csv"
df1 = pd.read_csv(url1)
df2 = pd.read_csv(url2)
df3 = pd.read_csv(url3)

Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount

Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Total Claim Amount,Policy Type,Vehicle Class

Customer,State,Customer Lifetime Value,Education,Gender,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Total Claim Amount,Vehicle Class

In [3]:
df1.columns =df1.columns.str.strip().str.lower().str.replace(" ","_")
df2.columns =df2.columns.str.strip().str.lower().str.replace(" ","_")
df3.columns =df3.columns.str.strip().str.lower().str.replace(" ","_")

In [10]:
df1.columns

Index(['customer', 'state', 'gender', 'education', 'customer_lifetime_value',
       'income', 'monthly_premium_auto', 'number_of_open_complaints',
       'policy_type', 'vehicle_class', 'total_claim_amount'],
      dtype='object')

In [11]:
df2.columns

Index(['customer', 'state', 'gender', 'education', 'customer_lifetime_value',
       'income', 'monthly_premium_auto', 'number_of_open_complaints',
       'total_claim_amount', 'policy_type', 'vehicle_class'],
      dtype='object')

In [12]:
df3.columns

Index(['customer', 'state', 'customer_lifetime_value', 'education', 'gender',
       'income', 'monthly_premium_auto', 'number_of_open_complaints',
       'policy_type', 'total_claim_amount', 'vehicle_class'],
      dtype='object')

In [8]:
df1=df1.rename(columns={'st': 'state'})

In [9]:
df2=df2.rename(columns={'st': 'state'})

In [14]:
df=pd.concat([df1, df2, df3], axis=0)
df.head()

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323

In [30]:
df["state"].unique()

array(['Washington', 'Arizona', 'Nevada', 'California', 'Oregon', nan],
      dtype=object)

In [27]:
df['state'] =df['state'].apply(lambda x:"Arizona" if x=="AZ" else x)

In [28]:
df['state'] =df['state'].apply(lambda x:"Washington" if x=="WA" else x)

In [29]:
df['state'] =df['state'].apply(lambda x:"California" if x=="Cali" else x)

In [26]:
df["gender"].unique()

array([nan, 'F', 'M'], dtype=object)

In [25]:
gender_mapping = {'male': 'M', 'female': 'F','Femal':'F', 'M':'M','F':'F'}
#gender_mapping = {'male': 'M', 'female': 'F','Femal':'F'}
df['gender']= df['gender'].map(gender_mapping)
df.gender.value_counts(dropna=False)

gender
F      4607
M      4368
NaN    3099
Name: count, dtype: int64

In [32]:
df["education"].unique()

array(['Master', 'Bachelor', 'High School or Below', 'College', 'Doctor',
       nan], dtype=object)

In [31]:
df['education'] =df['education'].apply(lambda x:"Bachelor" if x=="Bachelors" else x)

In [18]:
df["customer_lifetime_value"].unique()

array([nan, '697953.59%', '1288743.17%', ..., 8163.890428, 7524.442436,
       2611.836866], shape=(8212,), dtype=object)

In [33]:
df['customer_lifetime_value'] = df['customer_lifetime_value'].str.replace('%', '')
df

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323
...,...,...,...,...,...,...,...,...,...,...,...
7065,LA72316,California,M,Bachelor,NaN,71941.0,73.0,0,Personal Auto,Four-Door Car,198.234764
7066,PK87824,California,F,College,NaN,21604.0,79.0,0,Corporate Auto,Four-Door Car,379.200000
7067,TD14365,California,M,Bachelor,NaN,0.0,85.0,3,Corporate Auto,Four-Door Car,790.784983
7068,UP19263,California,M,College,NaN,21941.0,96.0,0,Personal Auto,Four-Door Car,691.200000
7069,Y167826,California,M,College,NaN,0.0,77.0,0,Corporate Auto,Two-Door Car,369.600000

In [36]:
df["customer_lifetime_value"].map(float)

0              NaN
1        697953.59
2       1288743.17
3        764586.18
4        536307.65
           ...
7065           NaN
7066           NaN
7067           NaN
7068           NaN
7069           NaN
Name: customer_lifetime_value, Length: 12074, dtype: float64

In [19]:
df["income"].unique()

array([    0., 48767., 36357., ..., 66367., 71941., 21941.], shape=(5656,))

In [20]:
df["monthly_premium_auto"].unique()

array([ 1000.,    94.,   108.,   106.,    68.,    69.,    67.,   101.,
          71.,    93.,   110.,    70.,    64.,    72.,    74.,    79.,
          73.,    61.,   111.,    80.,    63.,   237.,    65.,   130.,
          62.,   117.,    91.,    90.,    66.,    99.,   103., 35354.,
         172.,    92.,   104.,   113.,   124.,   105.,   100.,   112.,
          97.,    95.,   102.,    96.,   186.,    77.,    76.,   119.,
          87.,   109.,   107.,    88.,    85.,  6464.,   133.,    86.,
          78.,    89.,   192.,   118.,   140.,   127.,   126.,    82.,
         115.,   217.,   114.,   138.,    81.,   255.,   150.,   123.,
         116.,   190.,    98.,   159.,    84.,    83.,   152.,   136.,
         245.,   135.,  1005.,   225.,   132.,   153.,   121.,   139.,
         154.,   161.,   156.,   171.,   244.,   183.,   176.,   230.,
         129.,   177.,   181.,   196.,   131.,   276.,   253.,   137.,
         180.,   203.,   147.,   165.,   198.,   125.,   193.,   128.,
         271.,   142., 10202.,   206.,   182.,   189.,   160.,   295.,
         210.,   134., 35353.,   239.,   188.,   256.,   173.,   285.,
         148.,   141.,   197.,   199.,    nan,   214.,   175.,   167.,
         194.,   164.,   222.,   215.,   283.,   169.,   248.,   223.,
         151.,   213.,   145.,   185.,   287.,   297.,  5353.,   201.,
         149.,   146.,  7575.,   235.,   268.,   211.,   187.,   168.,
         122.,   143.,   155.,   166.,   212.,   249.,   240.,   191.,
         195.,   216.,   144.,   179.,   232.,   158.,   207.,   184.,
         238.,   229.,   220.,   178.,   204.,   281.,   170.,   234.,
         218.,   275.,   209.,   261.,   157.,   205.,   228.,   242.,
         284.,   231.,   208.,   296.,   202.,   162.,   274.,   219.,
         247.,   290.,   226.,   163.,   298.,   266.,   254.,   252.,
         174.,   286.])

In [38]:
df["number_of_open_complaints"].unique()

array(['0', '2', '1', '3', '5', '4', nan], dtype=object)

In [37]:
df['number_of_open_complaints'] = df['number_of_open_complaints'].str.split('/').str[1]
df

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,0,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59,0.0,94.0,0,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17,48767.0,108.0,0,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18,0.0,106.0,0,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65,36357.0,68.0,0,Personal Auto,Four-Door Car,17.269323
...,...,...,...,...,...,...,...,...,...,...,...
7065,LA72316,California,M,Bachelor,NaN,71941.0,73.0,NaN,Personal Auto,Four-Door Car,198.234764
7066,PK87824,California,F,College,NaN,21604.0,79.0,NaN,Corporate Auto,Four-Door Car,379.200000
7067,TD14365,California,M,Bachelor,NaN,0.0,85.0,NaN,Corporate Auto,Four-Door Car,790.784983
7068,UP19263,California,M,College,NaN,21941.0,96.0,NaN,Personal Auto,Four-Door Car,691.200000
7069,Y167826,California,M,College,NaN,0.0,77.0,NaN,Corporate Auto,Two-Door Car,369.600000

In [22]:
df["policy_type"].unique()

array(['Personal Auto', 'Corporate Auto', 'Special Auto', nan],
      dtype=object)

In [35]:
df["vehicle_class"].unique()

array(['Four-Door Car', 'Two-Door Car', 'SUV', 'Luxury', nan],
      dtype=object)

In [34]:
df['vehicle_class'] =df['vehicle_class'].apply(lambda x:"Luxury" if x in["Sports Car","Luxury SUV","Luxury Car"] else x)

In [24]:
df["total_claim_amount"].unique()

array([   2.704934, 1131.464935,  566.472247, ...,  541.282007,
        198.234764,  790.784983], shape=(5071,))

In [42]:
df.duplicated().sum()

np.int64(0)

In [41]:
df.drop_duplicates(inplace=True)

In [43]:
df

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,0,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59,0.0,94.0,0,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17,48767.0,108.0,0,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18,0.0,106.0,0,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65,36357.0,68.0,0,Personal Auto,Four-Door Car,17.269323
...,...,...,...,...,...,...,...,...,...,...,...
7065,LA72316,California,M,Bachelor,NaN,71941.0,73.0,NaN,Personal Auto,Four-Door Car,198.234764
7066,PK87824,California,F,College,NaN,21604.0,79.0,NaN,Corporate Auto,Four-Door Car,379.200000
7067,TD14365,California,M,Bachelor,NaN,0.0,85.0,NaN,Corporate Auto,Four-Door Car,790.784983
7068,UP19263,California,M,College,NaN,21941.0,96.0,NaN,Personal Auto,Four-Door Car,691.200000
7069,Y167826,California,M,College,NaN,0.0,77.0,NaN,Corporate Auto,Two-Door Car,369.600000

In [44]:
df=df.dropna(how='all')

In [45]:
df

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,0,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59,0.0,94.0,0,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17,48767.0,108.0,0,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18,0.0,106.0,0,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65,36357.0,68.0,0,Personal Auto,Four-Door Car,17.269323
...,...,...,...,...,...,...,...,...,...,...,...
7065,LA72316,California,M,Bachelor,NaN,71941.0,73.0,NaN,Personal Auto,Four-Door Car,198.234764
7066,PK87824,California,F,College,NaN,21604.0,79.0,NaN,Corporate Auto,Four-Door Car,379.200000
7067,TD14365,California,M,Bachelor,NaN,0.0,85.0,NaN,Corporate Auto,Four-Door Car,790.784983
7068,UP19263,California,M,College,NaN,21941.0,96.0,NaN,Personal Auto,Four-Door Car,691.200000
7069,Y167826,California,M,College,NaN,0.0,77.0,NaN,Corporate Auto,Two-Door Car,369.600000

# Challenge 2: Structuring Data

In this challenge, we will continue to work with customer data from an insurance company, but we will use a dataset with more columns, called marketing_customer_analysis.csv, which can be found at the following link:

https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis_clean.csv

This dataset contains information such as customer demographics, policy details, vehicle information, and the customer's response to the last marketing campaign. Our goal is to explore and analyze this data by performing data cleaning, formatting, and structuring.

In [46]:
url4="https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis_clean.csv"

df4= pd.read_csv(url4)

In [79]:
df4.columns

Index(['customer', 'state', 'customer_lifetime_value', 'response', 'coverage',
       'education', 'effective_to_date', 'employmentstatus', 'gender',
       'income', 'location_code', 'marital_status', 'monthly_premium_auto',
       'months_since_last_claim', 'months_since_policy_inception',
       'number_of_open_complaints', 'number_of_policies', 'policy_type',
       'policy', 'renew_offer_type', 'sales_channel', 'total_claim_amount',
       'vehicle_class', 'vehicle_size', 'vehicle_type', 'month'],
      dtype='object')

In [48]:
df4 = df4.drop('unnamed:_0', axis=1)

In [50]:
df4=df4.dropna(how='all')

In [52]:
df4.drop_duplicates(inplace=True)

In [54]:
df4["state"].unique()

array(['Arizona', 'California', 'Washington', 'Oregon', 'Nevada'],
      dtype=object)

In [55]:
df4["customer_lifetime_value"].unique()

array([ 4809.21696 ,  2228.525238, 14947.9173  , ...,  5259.444853,
       23893.3041  , 11971.97765 ], shape=(8041,))

In [56]:
df4["education"].unique()

array(['College', 'Bachelor', 'High School or Below', 'Doctor', 'Master'],
      dtype=object)

In [57]:
df4["gender"].unique()

array(['M', 'F'], dtype=object)

In [58]:
df4["education"].unique()

array(['College', 'Bachelor', 'High School or Below', 'Doctor', 'Master'],
      dtype=object)

In [59]:
df4["number_of_policies"].unique()

array([9, 1, 2, 7, 4, 3, 6, 8, 5])

In [60]:
df4["policy_type"].unique()

array(['Corporate Auto', 'Personal Auto', 'Special Auto'], dtype=object)

In [61]:
df4["policy"].unique()

array(['Corporate L3', 'Personal L3', 'Personal L2', 'Corporate L2',
       'Personal L1', 'Special L1', 'Corporate L1', 'Special L3',
       'Special L2'], dtype=object)

In [62]:
df4["renew_offer_type"].unique()

array(['Offer3', 'Offer4', 'Offer2', 'Offer1'], dtype=object)

In [63]:
df4["sales_channel"].unique()

array(['Agent', 'Call Center', 'Branch', 'Web'], dtype=object)

In [65]:
df4["total_claim_amount"].unique()

array([292.8     , 744.924331, 480.      , ..., 273.018929, 381.306996,
       618.288849], shape=(5106,))

In [69]:
df4["vehicle_class"].unique()

array(['Four-Door Car', 'SUV', 'Two-Door Car', 'Luxury'], dtype=object)

In [68]:
df4['vehicle_class'] =df4['vehicle_class'].apply(lambda x:"Luxury" if x in["Sports Car","Luxury SUV","Luxury Car"] else x)

In [70]:
df4["vehicle_size"].unique()

array(['Medsize', 'Small', 'Large'], dtype=object)

In [72]:
df4["vehicle_type"].unique()

array(['A'], dtype=object)

In [73]:
df4["month"].unique()

array([2, 1])

In [74]:
df4["income"].unique()

array([48029,     0, 22139, ..., 61146, 39837, 64195], shape=(5694,))

In [75]:
df4["employmentstatus"].unique()

array(['Employed', 'Unemployed', 'Medical Leave', 'Disabled', 'Retired'],
      dtype=object)

In [76]:
df4["effective_to_date"].unique()

array(['2011-02-18', '2011-01-18', '2011-02-10', '2011-01-11',
       '2011-01-17', '2011-02-14', '2011-02-24', '2011-01-19',
       '2011-01-04', '2011-01-02', '2011-02-07', '2011-01-31',
       '2011-01-26', '2011-02-28', '2011-01-16', '2011-02-26',
       '2011-02-23', '2011-01-15', '2011-02-02', '2011-02-15',
       '2011-01-24', '2011-02-21', '2011-02-22', '2011-01-07',
       '2011-01-28', '2011-02-08', '2011-02-12', '2011-02-20',
       '2011-01-05', '2011-02-19', '2011-01-03', '2011-02-03',
       '2011-01-22', '2011-01-23', '2011-02-05', '2011-02-13',
       '2011-01-25', '2011-02-16', '2011-02-01', '2011-01-27',
       '2011-01-12', '2011-01-20', '2011-02-06', '2011-02-11',
       '2011-01-21', '2011-01-29', '2011-01-09', '2011-02-09',
       '2011-02-27', '2011-01-01', '2011-02-17', '2011-02-25',
       '2011-01-13', '2011-01-06', '2011-02-04', '2011-01-14',
       '2011-01-10', '2011-01-08', '2011-01-30'], dtype=object)

In [77]:
df4["coverage"].unique()

array(['Basic', 'Extended', 'Premium'], dtype=object)

In [78]:
df4["response"].unique()

array(['No', 'Yes'], dtype=object)

In [80]:
df4["monthly_premium_auto"].unique()

array([ 61,  64, 100,  97, 117,  63, 154,  85, 127,  62,  99,  69, 116,
       114,  66,  73,  94, 104, 189,  74, 121, 110, 111,  72, 115, 159,
       101,  65,  82,  71, 126,  68, 199,  96,  67, 125, 249, 105,  92,
        78,  77,  79, 223, 242,  70, 102, 109, 107, 119, 194, 113, 106,
       247,  80,  86,  81,  83, 122, 253, 196, 132, 139,  84, 130,  93,
       103, 112, 222, 118,  88, 182, 283,  90, 128,  89, 235, 190,  76,
        87, 133, 153, 129,  98, 148, 123,  91, 211, 131, 108, 187, 214,
       181, 173, 252,  95, 124, 137, 145, 188, 143, 198, 138, 245, 195,
       186, 170, 136, 161, 157, 141, 205, 271, 192, 142, 140, 134, 240,
       185, 244, 210, 184, 202, 296, 213, 273, 219, 135, 169, 155, 225,
       266, 215, 197, 256, 212, 158, 180, 166, 168, 183, 162, 191, 179,
       150, 146, 276, 165, 239, 237, 193, 229, 274, 207, 295, 208, 172,
       217, 206, 201, 171, 152, 156, 174, 238, 167, 151, 144, 163, 287,
       209, 290, 220, 228, 232, 178, 177, 275, 176, 281, 149, 298, 255,
       216, 285, 226, 160, 147, 254, 164, 175, 297, 234, 284, 204, 218,
       261, 231, 248, 286, 230, 268, 203])

1. You work at the marketing department and you want to know which sales channel brought the most sales in terms of total revenue. Using pivot, create a summary table showing the total revenue for each sales channel (branch, call center, web, and mail).
Round the total revenue to 2 decimal points.  Analyze the resulting table to draw insights.

In [85]:
#pivot_df = df.pivot_table(index='country', columns='year', values=['GDP'], aggfunc='sum')

pivot_df4 = df4.pivot_table(columns='sales_channel', values=['customer_lifetime_value'], aggfunc='sum').round(2)

In [86]:
pivot_df4

              customer_lifetime_value
sales_channel                   Agent      Branch Call Center         Web
state
Arizona                    5586389.95  3891645.76  3102507.00  2279726.78
California                11737509.30  8972387.87  5939474.76  4403790.83
Nevada                     3289841.30  1980483.21  1614363.91  1105972.79
Oregon                     8585034.66  6543171.94  4626754.38  3483902.92
Washington                 2624095.76  2158169.97  1267331.00   845134.08

2. Create a pivot table that shows the average customer lifetime value per gender and education level. Analyze the resulting table to draw insights.

In [87]:
pivot_df5= df4.pivot_table(index='gender',columns='sales_channel', values=['customer_lifetime_value'], aggfunc='sum').round(2)
pivot_df5

              customer_lifetime_value
sales_channel                   Agent       Branch Call Center         Web
gender
F                         15811204.87  11980249.97  8686720.71  6708560.70
M                         16011666.09  11565608.77  7863710.34  5409966.69

In [88]:
pivot_df6= df4.pivot_table(index='education',columns='sales_channel', values=['customer_lifetime_value'], aggfunc='sum').round(2)
pivot_df6

                     customer_lifetime_value                          \
sales_channel                          Agent      Branch Call Center
education
Bachelor                          9449429.79  6352351.33  5223441.28
College                           8698261.67  7692892.11  4200913.47
Doctor                            1113059.16   723866.51   697029.47
High School or Below              9920928.21  6762578.20  5025408.15
Master                            2641192.14  2014170.59  1403638.68


sales_channel                Web
education
Bachelor              3419720.47
College               3635411.73
Doctor                 341733.73
High School or Below  3685479.27
Master                1036182.19

## Bonus

You work at the customer service department and you want to know which months had the highest number of complaints by policy type category. Create a summary table showing the number of complaints by policy type and month.
Show it in a long format table.

*In data analysis, a long format table is a way of structuring data in which each observation or measurement is stored in a separate row of the table. The key characteristic of a long format table is that each column represents a single variable, and each row represents a single observation of that variable.*

*More information about long and wide format tables here: https://www.statology.org/long-vs-wide-data/*

In [ ]:
# Your code goes here